dist: xenial
sudo: required
language: bash


before_install:

- curl https://raw.githubusercontent.com/Oturans/trytravis-work/ansible-3/config-scripts/install_all_travis.sh | bash
- curl https://kubernetes-helm.storage.googleapis.com/helm-v2.13.1-linux-amd64.tar.gz | tar zx

- sudo mv linux-amd64/helm /usr/bin/
- helm version --client


#terraform validate
- cd ./infra/terraform; terraform init -backend=false;
- terraform validate;
- tflint;
- cd ../..;

#Helm Lint

- cd ./infra/gitlab-omnibus && helm lint;
- cd ../..;
- cd ./infra/grafana && helm lint;
- cd ../..;
- cd ./infra/prometheus && helm lint;
- cd ../..;
- cd ./charts/mongo && helm lint;
- cd ../..;
- cd ./charts/mongoexporter && helm lint;
- cd ../..;
- cd ./charts/rabbit && helm lint;
- cd ../..;
- cd ./charts/search && helm lint;
- cd ../..;
- cd ./charts/crawler && helm lint;
- cd ../..;
- cd ./charts/ui && helm lint;

#docker: Check docker build
- cd src/search-engine-crawler && docker build -t test/crawler:1.0 .;
- cd ../..;
- cd src/search-engine-ui && docker build -t test/ui:1.0 .;


notifications:
  slack:
    rooms:
      secure: H6qr6EgPfkrmLHBPp8pHy/QceXx5UwaDHhcdYiVfqnrvyeeoWI8qTyGEbecxnmO6tuQYF00iAEcelrSeCedOJsv7FU/LftSA6A8M0vNrrHsUPvwj66OhqcUAcsxQ3A7ZO2SkpiPRr4WPWl+QkXQ8o8+0DKd2tNndfNeytXJ+WGaSE4lTaeDr4y6tldRuvZFchahz67uAtMUhKb+99Wkj915iv6hL97ZVMH+vR/4Oulzbxf7M6PKQ+wpHkbgjiMFxXNl2kVoXE/xMLrEkcWCeUnKTU2Hyx5o2zDXSmkAlKivm65VGo7nnto2N8DKHMxFMKJNmT04YvbWxf2dwnr2weYDN8wK4TEiYIKJAlgCytj7QkogcNwDjo2h/AchJf9U8x39zyVfXpDghKT5EXypv7mxNgGcKmmBjLDesUm+ZXxvrX/jQ/ICkAiTXk1UW/8MuxXaHyA4g14ptN+/WJ+tf1rHz+kEIcqGISaLv0YNpQoODMovOtVLjPDV7yaQhCK9BkMmSKLbWBtlt31S2g8pFqeCvz5ADOLI3SzC1Jl8GdMldQg2/4uv4npg7eNIBxrU/t+xPR4+aAHxUmV0tRLpGLoRUaXwhfLPSSpCtGHE3NFCwpX+QB/Xu3e9EBPh2gC1MfmybZ4B8HrvMVjw465SbakrHn3lqpvnI8DD7WlC05tU=
