dist: xenial
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/Oturans/project/master/install_for_travis.sh
  | bash
- cd ./infra/terraform; terraform init -backend=false;
- terraform validate;
- tflint;
- cd ../..;
- cd ./infra/gitlab-omnibus && helm lint;
- cd ../..;
- cd ./infra/grafana && helm lint;
- cd ../..;
- cd ./infra/prometheus && helm lint;
- cd ../..;
- cd ./charts/mongo && helm lint;
- cd ../..;
- cd ./charts/mongoexporter && helm lint;
- cd ../..;
- cd ./charts/rabbit && helm lint;
- cd ../..;
- cd ./charts/search && helm lint;
- cd ../..;
- cd ./charts/crawler && helm lint;
- cd ../..;
- cd ./charts/ui && helm lint;
- cd ../..;
- cd ./src/search-engine-crawler && docker build -t test/crawler:test .
- cd ../..;
- cd ./src/search-engine-ui && docker build -t test/ui:test .
notifications:
  slack:
    rooms:
      secure: QBl6+7P743txsx3bFe/H6HN86RO9ES2Qe2VRpfWWUZlOGZguurr8IgonCE6Nmchy75LMsH3OOyI931uAHzsn9UV9CkYSnrWUa1pefJZ9irNHp3L3vT7w8A9JlYWxdaKZ/Doyak0MUAdm992BWl8gNtP6brWYx5jdwyiSWxzqW7za+HBDE/1Mnava1ZiVWa6BwpszaJVBQtfdryIo/qL/leO1L9RYHtt4DwHyqtJiQJLEW/F5iL/wnwSNoJ1wv9nl2hgXLf9+9aqFUJKOqNop/U4I3Rr9HkAiZDffMGrEo/SfA74eyvdDCqFFN8JPDQByxTlBJ20fRfC8/wmMaZnqQm0akC/WMMInvPNbTo60xLlBc8t64r0ATRn+O7j5+AJhKQkeTZ8AERkKOrVtZkwu01eU+9jhBoDOvUMc7Sy3appW5PLfM2HyHf0cfBSkRBaDLFTiwA7pkTV6n73G7T6K0RDGWClmlhr4EmtsCL+Dhqr9zTctg3CHrdsaL1AZhe3HpTNVH0Wroge1zAKctv6+uHCB63S0fj4mDfdkrV6obV0F7xieGnGtTVyqzJEYSuFCnjCQjbCq/Yjz3DuYLGUXrBJHFwUabM5hp7t5yqAEh6rnMOP1UKPrTGb+FEbhTFv2KMGYlD7bESTGhMpP3v+dJzJZTyrsJ9kLOpfeSf/Joc8=
