dist: xenial
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/Oturans/project/master/install_for_travis.sh
  | bash
- cd ./infra/terraform; terraform init -backend=false;
- terraform validate;
- tflint;
- cd ../..;
- cd ./infra/gitlab-omnibus && helm lint;
- cd ../..;
- cd ./infra/grafana && helm lint;
- cd ../..;
- cd ./infra/prometheus && helm lint;
- cd ../..;
- cd ./charts/mongo && helm lint;
- cd ../..;
- cd ./charts/mongoexporter && helm lint;
- cd ../..;
- cd ./charts/rabbit && helm lint;
- cd ../..;
- cd ./charts/search && helm lint;
- cd ../..;
- cd ./charts/crawler && helm lint;
- cd ../..;
- cd ./charts/ui && helm lint;
- cd ../..;
- cd ./src/search-engine-crawler && docker build -t test/crawler:test .
- cd ../..;
- cd ./src/search-engine-ui && docker build -t test/ui:test .
notifications:
  slack:
    rooms:
      secure: LavExKfPAkipgvQWIhOXtWFbv0byFp5oNZqRGAMgZkRDJZAakHot6g2mvhUByU0wVs6kepu73O3wkG50P6PgpqqDxPtt7NnK1okpKeyOd3f5I+WXYBjIvk/DZTFRvfv/bzCnb4xe8h5SQ8a8spxsunwsPfUDAU+00djSgEHiNd6tIYMgczAF7926tNK/ioS7cjJ9UxEcdb52S7dkaspB+FX9Y/gnN5M35/z/0YKXG75+OqEtkTzK43FSqqFAE+xKEzHDl50oSfxW6cczr5SExLLm/agO/gI+ZnX+GlhCki+CwOW5xiOjLgAWiSLACPZDCJpXuqSQkxYUm+IKi4SVCCLpX8gt+7dIFzRd/B1W4c1MMneDUWduqZ5F2Bo3Sf8Bp78Alr+KD30zmxEE9WqZEEEbmdlXJAqJstjij1bQ+leaio63YaRF4X0la7eEGpEQwJq4UoCvzksy2+z5rfOsTDXEv3q04bu6uI0zgUVR1JHephb+TB9OH4xtjRT75u9FIetdQ2+YxkKzQ2OPuw8smIa2G7f5WLo0Ct+3MzwoBp44abPyLPpq4BOs1QLW4fJDtsCbOY8uPYCz/yUJU/XRDPIZ9RxU4tggPCZG6K8yYBfbRO8vudv7MWUYC5VO3vvsCm/gdX7PAKo7YZO9PgaHMnH3suLWNU+470ezeEz3GRw=
