---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbit.fullname" . }}
  labels:
    app: search
    component: rabbit
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: search
    component: rabbit
    release: {{ .Release.Name }}
