version: '3.3'
services:
  mongo:
    image: mongo
    networks:
      - net

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 8080:15672/tcp
    networks:
      - net

  crawler:
    build: ./search-engine-crawler
    image: oturans/search-engine-crawler
    environment:
      - MONGO=mongo
      - RMQ_HOST=rabbit
    ports:
      - 8000:8000/tcp
    depends_on:
      - rabbit
      - mongo
    networks:
      - net

  ui:
    build: ./search-engine-ui
    image: oturans/search-engine-ui
    environment:
      - MONGO=mongo
    depends_on:
      - mongo
    ports:
      - 8000:8000/tcp
    networks:
      - net

networks:
  net:
